{
 "title": "AI Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "CPU and GPU Utilization (avg)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"ai-visibility\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia_smi\")\n  |> filter(fn: (r) => r[\"_field\"] == \"utilization_gpu\")\n  |> group(columns: [\"pstate\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")"
    },
    { "expression": "100-$A", "type": "math" }
   ]
  },
  {
   "title": "Requests (concurrent)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ai-visibility\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vllm:num_requests_running\")\n  |> filter(fn: (r) => r[\"host\"] == \"ai-11\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "LLM Use (Tokens/sec)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ai-visibility\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vllm:avg_generation_throughput_toks_per_s\")\n  |> filter(fn: (r) => r[\"host\"] == \"ai-11\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")\n  "
    }
   ]
  },
  {
   "title": "Switch Interface Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "query": "from(bucket: \"ai-visibility\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_stats\")\n   |> filter(fn: (r) => r[\"source\"] == \"64.101.226.2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"in_octets\")\n  |> filter(fn: (r) => r[\"name\"] == \"eth1/1\" or r[\"name\"] == \"eth1/2\")\n  |> map(fn: (r) => ({r with _value: r._value * 8}))\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")\n  |> aggregateWindow(every: 30s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"ai-visibility\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_stats\")\n   |> filter(fn: (r) => r[\"source\"] == \"64.101.226.3\")\n  |> filter(fn: (r) => r[\"_field\"] == \"in_octets\")\n  |> filter(fn: (r) => r[\"name\"] == \"eth1/1\" or r[\"name\"] == \"eth1/2\")\n  |> map(fn: (r) => ({r with _value: r._value * 8}))\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")\n  |> aggregateWindow(every: 30s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "API Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ai-visibility\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_response\")\n  |> filter(fn: (r) => r[\"_field\"] == \"result_code\")\n  |> filter(fn: (r) => r[\"host\"] == \"ai-11\")\n  |> group()\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ai-visibility\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia_smi\")\n  |> filter(fn: (r) => r[\"_field\"] == \"utilization_gpu\")\n  |> drop(columns: [\"pstate\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")\n  "
    }
   ]
  },
  {
   "title": "GPU Memory Utilization",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/1000", "type": "math" }
   ]
  }
 ]
}