services:
    telegraf:
        image: telegraf
        container_name: telegraf
        restart: always
        privileged: true
        env_file:
            - influxv2.env
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
            # - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - influxdb
        ports:
            - '8125:8125'
    influxdb:
        image: influxdb:2.7.10-alpine
        container_name: influxdb
        env_file:
            - influxv2.env
        volumes:
            - influxdb_data:/var/lib/influxdb
        ports:
            - '8086:8086'
    grafana:
        image: grafana/grafana
        container_name: grafana-server
        restart: always
        depends_on:
            - influxdb
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_INSTALL_PLUGINS=
        volumes:
            - grafana_data:/var/lib/grafana
        ports:
            - '3000:3000'

volumes:
    influxdb_data:
    grafana_data: