services:
    # Optional Telegraf Container can comment out or remove if desired
    telegraf:
        image: telegraf
        container_name: telegraf
        restart: always
        privileged: true
        env_file:
            - influxv2.env
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
        depends_on:
            - influxdb
        ports:
            - '8125:8125'
    influxdb:
        image: influxdb:2.7.10-alpine
        container_name: influxdb
        env_file:
            - influxv2.env
        volumes:
            - influxdb_data:/var/lib/influxdb
        ports:
            - '8086:8086'
    grafana:
        image: grafana/grafana
        container_name: grafana-server
        restart: always
        env_file:
            - grafana.env
        depends_on:
            - influxdb
        volumes:
            - grafana_data:/var/lib/grafana
        ports:
            - '3000:3000'

volumes:
    influxdb_data:
    grafana_data: